<a href="https://colab.research.google.com/github/WillianSCorrea/am-t4-s1a2026/blob/main/aula2403_amt4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução de Python

In [ ]:
a=2
b=3
print('A soma é:', a+b)

A soma é: 5

## Segunda Camada

In [ ]:
c=4
d=5
print('A multiplicação é:',c*d)

A multiplicação é: 20

# Bibliotecas e Funções de Python

In [ ]:
import math

def equacao2grau(a,b,c):
  delta = b**2 - 4*a*c

  if delta < 0 :
    return 'Numeros sem Raiz', delta

  x1 = (-b + math.sqrt(delta))/(2*a)
  x2 = (-b - math.sqrt(delta))/(2*a)

  return x1,x2

## Teste de Função Matemática

In [ ]:
eq = equacao2grau(1, -3 , 2)
print(eq)

(2.0, 1.0)

In [ ]:
import random

for i in range(5):
  a = random.randint(-5 , 5)
  b = random.randint(-10,10)
  c = random.randint(- 10,-10)
  eq += equacao2grau(a, b , c)

In [ ]:
for i in range(22):
  if i % 2 == 0:
    if eq[i] != 'Numeros sem Raiz':
      print('x1 :[' ,eq[i],']')
  else:
    if eq[i] != 'Numeros sem Raiz':
      print('x2 : [' ,eq[i],']\n')

x1 :[ 2.0 ]
x2 : [ 1.0 ]

x1 :[ 2.0 ]
x2 : [ -5.0 ]

x2 : [ -119 ]

x2 : [ -199 ]

x2 : [ -40 ]

x1 :[ 5.0 ]
x2 : [ -2.0 ]

x2 : [ -64 ]

x1 :[ 1.0 ]
x2 : [ -2.5 ]

x2 : [ -175 ]

x2 : [ -124 ]

x1 :[ -6.449489742783178 ]
x2 : [ -1.5505102572168221 ]

# Trabalho com Dados Externos

### Biblioteca de uso da pipeline

In [1]:
!pip -q install plotly
!pip install yellowbrick

Requirement already satisfied: yellowbrick in /usr/local/lib/python3.12/dist-packages (1.5)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (3.10.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (1.6.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (2.0.2)
Requirement already satisfied: cycler>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.9.0.post0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->yellowbrick) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->yellowbrick) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
from  google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
base_credit = pd.read_csv('/content/drive/MyDrive/am-e4/credit_data.csv')

In [6]:
base_credit

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [10]:
base_credit.describe()

          clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [ ]:
base_credit.head(10)

In [ ]:
base_credit.tail(10)

In [7]:
base_credit[base_credit['income'] < 65500]

      clientid        income        age         loan  default
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
5            6  24904.064140  57.471607    15.498598        0
6            7  48430.359613  26.809132  5722.581981        0
...        ...           ...        ...          ...      ...
1993      1994  54421.410155  26.821928  3273.631823        0
1994      1995  24254.700791  37.751622  2225.284643        0
1995      1996  59221.044874  48.518179  1926.729397        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0

[1820 rows x 5 columns]

In [8]:
base_credit[base_credit['loan'] <= 1.377630]

     clientid        income        age     loan  default
865       866  28072.604355  54.142548  1.37763        0

# Análise de Anomalias Exploraria

## Analise de Anomalia Idade Negativa

In [9]:
base_credit[base_credit['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0